name: Tag Release

on:
  push:
    branches:
      - main

permissions:
  contents: write #
jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Read version from package.json and create tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG="v$VERSION"

          echo "Tag to create: $TAG"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag $TAG
          git push origin $TAG
